FROM pypy:2

WORKDIR /usr/src/app/
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
COPY supervisor/supervisord-dev.conf /etc/supervisor/conf.d/supervisord.conf
RUN apt-get update \
  && apt-get install locales -y \
  && apt-get install cron -y \
  && apt-get install vim-nox -y \
  && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
  && sed -i -e 's/# es_CO.UTF-8 UTF-8/es_CO.UTF-8 UTF-8/' /etc/locale.gen \
  && dpkg-reconfigure --frontend=noninteractive locales \
  && mkdir -p /var/log/supervisord \
  && apt-get install -y supervisor \
  && apt-get clean \
  && apt-get autoremove

ENV FLASK_APP main.py
ENV FLASK_DEBUG True
ENV FLASK_ENV development
ENV GUWORKERS_CONNECTIONS 1001
ENV GUWORKERS 4
ENV APP_NAME server
ENV APP_PORT 8077

ENTRYPOINT ["supervisord"]
